# Generated by Django 4.2.5 on 2024-01-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listings_image_listingimage_listings_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='images',
        ),
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ListingImage',
        ),
    ]
