# Generated by Django 5.0 on 2024-02-27 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listings_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('razorpay_payment_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listings')),
            ],
        ),
    ]
