# Generated by Django 5.0 on 2024-02-08 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listings_contact'),
        ('properties', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listings'),
        ),
    ]
