# Generated by Django 5.0 on 2024-02-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_msg_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msg',
            name='listing',
        ),
    ]
