# Generated by Django 5.0 on 2024-02-08 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listings_contact'),
        ('properties', '0004_remove_msg_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='listing_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='listings.listings'),
            preserve_default=False,
        ),
    ]
