# Generated by Django 5.0 on 2024-02-08 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listings_contact'),
        ('properties', '0005_msg_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='listing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listings'),
        ),
    ]
