# Generated by Django 5.0 on 2024-02-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_msg_listing_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msg',
            name='listing_id',
        ),
    ]
